### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library

### ISSUE THREAD

**Issue by tvvoty** [bonigarcia/dualsub#22]
Os: Kubuntu 21.04

Java version:
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)

When I try to open the app with terminal I get this error:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
        at com.jgoodies.plaf.LookUtils.isLowResolution(LookUtils.java:405)
        at com.jgoodies.plaf.LookUtils.<clinit>(LookUtils.java:174)
        at com.jgoodies.plaf.plastic.PlasticLookAndFeel.<clinit>(PlasticLookAndFeel.java:122)
        at io.github.bonigarcia.dualsub.gui.DualSub.<init>(DualSub.java:125)
        at io.github.bonigarcia.dualsub.gui.DualSub.main(DualSub.java:550)
```

**Comment by tvvoty** [comment]
Ok, I just had to install "openjdk-11-jdk" from the repository. Apparently, java wasn't actually installed? Or maybe stock java that came with the system just didn't have that specific library.

**Comment by bonigarcia** [comment]
Indeed, you need Java to run DualSub.
